# Generated by Django 4.0.4 on 2022-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/groups/', verbose_name='Аватарка'),
        ),
    ]
