# Generated by Django 4.0.4 on 2022-04-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_group_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupUser',
        ),
    ]
