# Generated by Django 4.0.4 on 2022-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_groupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default/group.jpg', null=True, upload_to='static/images/groups/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default/user.jpg', null=True, upload_to='static/images/users/', verbose_name='Аватарка'),
        ),
    ]
